"""Export transformed fundamentals as Postgres-ready Parquet plus matching DDL.

DuckDB stays the working store; this module only produces a handoff artifact.
The single long `fundamental_metrics` table is split into the three shapes it
actually holds — scalar metrics, financial statement lines, and profile
entries — because each has a different natural key.

Numbers in `fundamental_metrics` are unit-collapsed: 7.51 may be a percentage,
13.10 a ratio and 1.4684e13 rupiah, all in one DOUBLE. Every exported row
therefore carries a `unit` so the Postgres side never has to infer it from the
metric name.
"""
from __future__ import annotations

import logging
import re
from pathlib import Path

import duckdb
import pandas as pd

from agent_idx.transforms import _LOCK, connect, init_schema

logger = logging.getLogger(__name__)

DEFAULT_OUT = Path("exports/postgres")

PROFILE_SECTIONS = frozenset(
    {
        "address",
        "board of commissioners",
        "board of directors",
        "company background",
        "company history",
        "company info",
        "directors and commissioners ownership",
        "holding composition",
        "number of shareholders",
        "other tables",
        "profile fields",
        "profile structured",
        "shareholder > 1%",
        "shareholder composition",
        "shareholders",
        "subsidiary companies",
        "ultimate beneficiary owner",
    }
)

_STATEMENT_PREFIXES = ("statement:", "ratio:", "series:")
_SECTION_SPLIT = re.compile(
    r"^(?:statement|ratio|series):\s*(.+?)(?:\s*\(([^)]+)\))?$", re.I
)
_MAGNITUDE = re.compile(r"[\d)]\s*[KMBT]\b")
_PER_SHARE = re.compile(r"per share|^eps\b|\beps\b|dividend", re.I)
_RATIO_WORDS = re.compile(
    r"ratio|margin|yield|score|rating|rank|turnover|leverage|coverage"
    r"|growth|cagr|multiple|\bpe\b|\bpbv\b",
    re.I,
)
_SHARE_COUNT = re.compile(r"\bshares?\b|share outstanding|float", re.I)
# The Price Performance block pairs badly, leaving rows whose "metric" is just a
# figure — "(-15.20%)" with the 52-week low as its value. A bare number is never
# a metric name, so these are the one class of row worth dropping outright.
_NOT_A_METRIC = re.compile(r"^\(?[-+]?[\d.,]+\s*%?\)?$")


def _section_trust(section: str) -> int:
    """Rank sources for the same metric; the keystats page repeats itself.

    A scalar like Market Cap surfaces under several headings with an identical
    value, so one has to win. The structured extractor is the most reliable and
    the free-text dump the least.
    """
    if section == "raw page text":
        return 3
    if section == "tables (visible)":
        return 2
    if section.startswith(_STATEMENT_PREFIXES):
        return 1
    return 0


def _split_section(section: str) -> tuple[str, str]:
    """`statement:income statement (quarterly)` -> (income statement, quarterly)."""
    m = _SECTION_SPLIT.match(section or "")
    if not m:
        return (section or "").strip(), ""
    return m.group(1).strip(), (m.group(2) or "").strip().lower()


_PERIOD_TYPE_ALIASES = {
    "quarter": "quarterly",
    "quarterly": "quarterly",
    "year": "annual",
    "yearly": "annual",
    "annual": "annual",
    "interim": "interim",
    "interim ytd": "interim",
    "ttm": "ttm",
    "ltm": "ttm",
}


def _normalise_period_type(value: str) -> str:
    """One vocabulary, whether the label came from the section or the period."""
    v = (value or "").strip().lower()
    return _PERIOD_TYPE_ALIASES.get(v, v)


def _period_type_from(period: str) -> str:
    p = (period or "").strip()
    if not p:
        return ""
    if re.fullmatch(r"Q[1-4]\s+\d{4}", p, re.I):
        return "quarterly"
    if re.fullmatch(r"12M\s+\d{4}", p, re.I):
        return "annual"
    if re.fullmatch(r"\d{1,2}M\s+\d{4}", p, re.I):
        return "interim"
    if re.fullmatch(r"\d{4}", p):
        return "annual"
    if re.fullmatch(r"TTM|LTM", p, re.I):
        return "ttm"
    return "other"


def _unit_for(metric: str, value_raw: object, value_num: object) -> str:
    """Classify what a figure measures: idr, pct, ratio, shares, number, text."""
    if value_num is None or pd.isna(value_num):
        return "text"
    raw = str(value_raw or "").strip()
    if raw.endswith("%"):
        return "pct"
    low = str(metric or "").lower()
    if _PER_SHARE.search(low):
        return "idr_per_share"
    if _SHARE_COUNT.search(low):
        return "shares"
    if _MAGNITUDE.search(raw) or re.fullmatch(r"-?[\d,]{9,}(\.\d+)?", raw):
        return "idr"
    if _RATIO_WORDS.search(low):
        return "ratio"
    return "number"


SCHEMA_SQL = """\
-- Postgres DDL matching the Parquet files in this directory.
-- Generated by agent_idx.pg_export; safe to edit on the Postgres side.
--
-- as_of is the scrape date (provenance), NOT the reporting date. For statement
-- lines the meaningful time axis is `period`, which is why as_of is kept out of
-- the primary keys below.
--
-- unit tells you what value_num measures:
--   idr            absolute rupiah (already multiplied out, not "in billions")
--   idr_per_share  rupiah per share (EPS, DPS, book value per share)
--   pct            percent as written, e.g. 7.51 means 7.51%, not 0.0751
--   ratio          dimensionless (PE, PBV, Z-score)
--   shares         a share count
--   number         a plain number with no unit attached
--   text           value_num is NULL; read value_raw

CREATE TABLE IF NOT EXISTS fundamental_metric (
    symbol      TEXT        NOT NULL,
    as_of       DATE        NOT NULL,
    section     TEXT        NOT NULL,
    metric      TEXT        NOT NULL,
    period      TEXT        NOT NULL DEFAULT '',
    unit        TEXT        NOT NULL,
    value_raw   TEXT,
    value_num   NUMERIC,
    -- section is provenance only: the same metric appears under several
    -- headings on the keystats page and the export keeps the best source.
    PRIMARY KEY (symbol, metric, period)
);

CREATE TABLE IF NOT EXISTS financial_statement_line (
    symbol      TEXT        NOT NULL,
    as_of       DATE        NOT NULL,
    statement   TEXT        NOT NULL,
    period_type TEXT        NOT NULL,
    period      TEXT        NOT NULL,
    line_item   TEXT        NOT NULL,
    unit        TEXT        NOT NULL,
    currency    TEXT        NOT NULL DEFAULT 'IDR',
    value       NUMERIC,
    value_raw   TEXT,
    PRIMARY KEY (symbol, statement, period_type, period, line_item)
);

CREATE TABLE IF NOT EXISTS company_profile (
    symbol      TEXT        NOT NULL,
    as_of       DATE        NOT NULL,
    category    TEXT        NOT NULL,
    item        TEXT        NOT NULL,
    unit        TEXT        NOT NULL,
    value_raw   TEXT,
    value_num   NUMERIC,
    PRIMARY KEY (symbol, category, item)
);

CREATE INDEX IF NOT EXISTS financial_statement_line_symbol_period_idx
    ON financial_statement_line (symbol, period_type, period);
CREATE INDEX IF NOT EXISTS fundamental_metric_symbol_idx
    ON fundamental_metric (symbol);
"""


def _read_metrics(symbols: list[str] | None) -> pd.DataFrame:
    with _LOCK:
        con = connect()
        try:
            init_schema(con)
            df = con.execute(
                """
                SELECT symbol, as_of, section, metric, period, value_raw, value_num
                FROM fundamental_metrics
                """
            ).df()
        finally:
            con.close()
    if symbols:
        wanted = {s.strip().upper() for s in symbols if s.strip()}
        df = df[df["symbol"].isin(wanted)]
    return df


def _currency_by_symbol(df: pd.DataFrame) -> dict[str, str]:
    meta = df[
        (df["section"] == "financials meta")
        & (df["metric"].str.lower() == "unit")
    ]
    out: dict[str, str] = {}
    for row in meta.itertuples():
        out[row.symbol] = "USD" if "USD" in str(row.value_raw).upper() else "IDR"
    return out


def export_fundamentals(
    *,
    out_dir: str | Path | None = None,
    symbols: list[str] | None = None,
) -> str:
    """Write the three Postgres-ready Parquet files plus schema.sql."""
    out = Path(out_dir) if out_dir else DEFAULT_OUT
    out.mkdir(parents=True, exist_ok=True)

    df = _read_metrics(symbols)
    if df.empty:
        return (
            "export fundamentals: 0 rows in fundamental_metrics.\n"
            "Run farm_stockbit_fundamentals then "
            "run_data_transform(scope='fundamentals') first."
        )

    df["as_of"] = pd.to_datetime(df["as_of"], errors="coerce").dt.date
    df["period"] = df["period"].fillna("")
    dropped = df["metric"].str.match(_NOT_A_METRIC).fillna(False)
    df = df[~dropped]
    df["unit"] = [
        _unit_for(m, vr, vn)
        for m, vr, vn in zip(df["metric"], df["value_raw"], df["value_num"])
    ]
    currency = _currency_by_symbol(df)

    # Scalar rows picked up alongside a statement or series table have no
    # period, and a statement line without a period is not a statement line.
    is_fin = df["section"].str.startswith(_STATEMENT_PREFIXES) & df["period"].ne("")
    is_prof = df["section"].isin(PROFILE_SECTIONS) & ~is_fin

    fin_src = df[is_fin]
    split = [_split_section(s) for s in fin_src["section"]]
    fin = pd.DataFrame(
        {
            "symbol": fin_src["symbol"].values,
            "as_of": fin_src["as_of"].values,
            "statement": [s for s, _ in split],
            "period_type": [
                _normalise_period_type(pt) or _period_type_from(p)
                for (_, pt), p in zip(split, fin_src["period"])
            ],
            "period": fin_src["period"].values,
            "line_item": fin_src["metric"].values,
            "unit": fin_src["unit"].values,
            "currency": [currency.get(s, "IDR") for s in fin_src["symbol"]],
            "value": fin_src["value_num"].values,
            "value_raw": fin_src["value_raw"].values,
        }
    ).drop_duplicates(
        subset=["symbol", "statement", "period_type", "period", "line_item"]
    )

    prof_src = df[is_prof]
    prof = pd.DataFrame(
        {
            "symbol": prof_src["symbol"].values,
            "as_of": prof_src["as_of"].values,
            "category": prof_src["section"].values,
            "item": prof_src["metric"].values,
            "unit": prof_src["unit"].values,
            "value_raw": prof_src["value_raw"].values,
            "value_num": prof_src["value_num"].values,
        }
    ).drop_duplicates(subset=["symbol", "category", "item"])

    met = df[~is_fin & ~is_prof][
        ["symbol", "as_of", "section", "metric", "period", "unit", "value_raw", "value_num"]
    ].copy()
    met["_trust"] = [_section_trust(s) for s in met["section"]]
    met = (
        met.sort_values("_trust", kind="stable")
        .drop_duplicates(subset=["symbol", "metric", "period"])
        .drop(columns="_trust")
        .sort_values(["symbol", "section", "metric"])
    )

    written: list[tuple[str, int]] = []
    # DuckDB writes the parquet so the project keeps working without pyarrow.
    writer = duckdb.connect()
    try:
        for name, frame in (
            ("fundamental_metric", met),
            ("financial_statement_line", fin),
            ("company_profile", prof),
        ):
            path = out / f"{name}.parquet"
            writer.register("frame", frame)
            writer.execute(
                f"COPY (SELECT * FROM frame) TO '{path.as_posix()}' (FORMAT PARQUET)"
            )
            writer.unregister("frame")
            written.append((name, len(frame)))
    finally:
        writer.close()

    (out / "schema.sql").write_text(SCHEMA_SQL, encoding="utf-8")

    n_symbols = df["symbol"].nunique()
    lines = [
        f"export fundamentals -> {out}",
        f"symbols={n_symbols} source_rows={len(df)} "
        f"dropped_unnamed={int(dropped.sum())}",
        "",
    ]
    lines += [f"- {name}.parquet: {n} rows" for name, n in written]
    lines.append("- schema.sql: CREATE TABLE DDL for Postgres")
    lines.append("")
    lines.append(f"SAVED: {out / 'schema.sql'}")
    return "\n".join(lines)
