"""Export transformed fundamentals as Postgres-ready Parquet plus matching DDL.

DuckDB stays the working store; this module only produces a handoff artifact.
The single long `fundamental_metrics` table is split into the three shapes it
actually holds — scalar metrics, financial statement lines, and profile
entries — because each has a different natural key.

Numbers in `fundamental_metrics` are unit-collapsed: 7.51 may be a percentage,
13.10 a ratio and 1.4684e13 rupiah, all in one DOUBLE. Every exported row
therefore carries a `unit` so the Postgres side never has to infer it from the
metric name.
"""
from __future__ import annotations

import logging
import re
from pathlib import Path

import duckdb
import pandas as pd

from agent_idx.transforms import _LOCK, connect, init_schema

logger = logging.getLogger(__name__)

DEFAULT_OUT = Path("exports/postgres")

PROFILE_SECTIONS = frozenset(
    {
        "address",
        "board of commissioners",
        "board of directors",
        "company background",
        "company history",
        "company info",
        "directors and commissioners ownership",
        "holding composition",
        "number of shareholders",
        "other tables",
        "profile fields",
        "profile structured",
        "shareholder > 1%",
        "shareholder composition",
        "shareholders",
        "subsidiary companies",
        "ultimate beneficiary owner",
    }
)

_STATEMENT_PREFIXES = ("statement:", "ratio:", "series:")
_SECTION_SPLIT = re.compile(
    r"^(?:statement|ratio|series):\s*(.+?)(?:\s*\(([^)]+)\))?$", re.I
)
_MAGNITUDE = re.compile(r"[\d)]\s*[KMBT]\b")
_PER_SHARE = re.compile(r"per share|^eps\b|\beps\b|dividend", re.I)
_RATIO_WORDS = re.compile(
    r"ratio|margin|yield|score|rating|rank|turnover|leverage|coverage"
    r"|growth|cagr|multiple|\bpe\b|\bpbv\b",
    re.I,
)
_SHARE_COUNT = re.compile(r"\bshares?\b|share outstanding|float", re.I)
# The Price Performance block pairs badly, leaving rows whose "metric" is just a
# figure — "(-15.20%)" with the 52-week low as its value. A bare number is never
# a metric name, so these are the one class of row worth dropping outright.
_NOT_A_METRIC = re.compile(r"^\(?[-+]?[\d.,]+\s*%?\)?$")


def _section_trust(section: str) -> int:
    """Rank sources for the same metric; the keystats page repeats itself.

    A scalar like Market Cap surfaces under several headings with an identical
    value, so one has to win. The structured extractor is the most reliable and
    the free-text dump the least.
    """
    if section == "raw page text":
        return 3
    if section == "tables (visible)":
        return 2
    if section.startswith(_STATEMENT_PREFIXES):
        return 1
    return 0


def _split_section(section: str) -> tuple[str, str]:
    """`statement:income statement (quarterly)` -> (income statement, quarterly)."""
    m = _SECTION_SPLIT.match(section or "")
    if not m:
        return (section or "").strip(), ""
    return m.group(1).strip(), (m.group(2) or "").strip().lower()


_PERIOD_TYPE_ALIASES = {
    "quarter": "quarterly",
    "quarterly": "quarterly",
    "year": "annual",
    "yearly": "annual",
    "annual": "annual",
    "interim": "interim",
    "interim ytd": "interim",
    "ttm": "ttm",
    "ltm": "ttm",
}


def _normalise_period_type(value: str) -> str:
    """One vocabulary, whether the label came from the section or the period."""
    v = (value or "").strip().lower()
    return _PERIOD_TYPE_ALIASES.get(v, v)


def _period_type_from(period: str) -> str:
    p = (period or "").strip()
    if not p:
        return ""
    if re.fullmatch(r"Q[1-4]\s+\d{4}", p, re.I):
        return "quarterly"
    if re.fullmatch(r"12M\s+\d{4}", p, re.I):
        return "annual"
    if re.fullmatch(r"\d{1,2}M\s+\d{4}", p, re.I):
        return "interim"
    if re.fullmatch(r"\d{4}", p):
        return "annual"
    if re.fullmatch(r"TTM|LTM", p, re.I):
        return "ttm"
    return "other"


def _unit_for(metric: str, value_raw: object, value_num: object) -> str:
    """Classify what a figure measures: idr, pct, ratio, shares, number, text."""
    if value_num is None or pd.isna(value_num):
        return "text"
    raw = str(value_raw or "").strip()
    if raw.endswith("%"):
        return "pct"
    low = str(metric or "").lower()
    if _PER_SHARE.search(low):
        return "idr_per_share"
    if _SHARE_COUNT.search(low):
        return "shares"
    if _MAGNITUDE.search(raw) or re.fullmatch(r"-?[\d,]{9,}(\.\d+)?", raw):
        return "idr"
    if _RATIO_WORDS.search(low):
        return "ratio"
    return "number"


SCHEMA_SQL = """\
-- Postgres DDL matching the Parquet files in this directory.
-- Generated by agent_idx.pg_export; safe to edit on the Postgres side.
--
-- as_of is the scrape date (provenance), NOT the reporting date. For statement
-- lines the meaningful time axis is `period`, which is why as_of is kept out of
-- the primary keys below.
--
-- unit tells you what value_num measures:
--   idr            absolute rupiah (already multiplied out, not "in billions")
--   idr_per_share  rupiah per share (EPS, DPS, book value per share)
--   pct            percent as written, e.g. 7.51 means 7.51%, not 0.0751
--   ratio          dimensionless (PE, PBV, Z-score)
--   shares         a share count
--   number         a plain number with no unit attached
--   text           value_num is NULL; read value_raw

CREATE TABLE IF NOT EXISTS fundamental_metric (
    symbol      TEXT        NOT NULL,
    as_of       DATE        NOT NULL,
    section     TEXT        NOT NULL,
    metric      TEXT        NOT NULL,
    period      TEXT        NOT NULL DEFAULT '',
    unit        TEXT        NOT NULL,
    value_raw   TEXT,
    value_num   NUMERIC,
    -- section is provenance only: the same metric appears under several
    -- headings on the keystats page and the export keeps the best source.
    PRIMARY KEY (symbol, metric, period)
);

CREATE TABLE IF NOT EXISTS financial_statement_line (
    symbol      TEXT        NOT NULL,
    as_of       DATE        NOT NULL,
    statement   TEXT        NOT NULL,
    period_type TEXT        NOT NULL,
    period      TEXT        NOT NULL,
    line_item   TEXT        NOT NULL,
    unit        TEXT        NOT NULL,
    currency    TEXT        NOT NULL DEFAULT 'IDR',
    value       NUMERIC,
    value_raw   TEXT,
    PRIMARY KEY (symbol, statement, period_type, period, line_item)
);

CREATE TABLE IF NOT EXISTS company_profile (
    symbol      TEXT        NOT NULL,
    as_of       DATE        NOT NULL,
    category    TEXT        NOT NULL,
    item        TEXT        NOT NULL,
    unit        TEXT        NOT NULL,
    value_raw   TEXT,
    value_num   NUMERIC,
    PRIMARY KEY (symbol, category, item)
);

CREATE INDEX IF NOT EXISTS financial_statement_line_symbol_period_idx
    ON financial_statement_line (symbol, period_type, period);
CREATE INDEX IF NOT EXISTS fundamental_metric_symbol_idx
    ON fundamental_metric (symbol);

-- Chart bars (tvkit) — one row per symbol/timeframe/ts. Sourced from
-- data/charts/{SYMBOL}/{TF}.parquet via export_ohlcv.
CREATE TABLE IF NOT EXISTS ohlcv (
    symbol       TEXT           NOT NULL,
    timeframe    TEXT           NOT NULL,
    ts           BIGINT         NOT NULL,
    datetime     TEXT,
    date         INTEGER,
    open         DOUBLE PRECISION,
    high         DOUBLE PRECISION,
    low          DOUBLE PRECISION,
    close        DOUBLE PRECISION,
    volume       DOUBLE PRECISION,
    sma_5        DOUBLE PRECISION,
    sma_20       DOUBLE PRECISION,
    sma_50       DOUBLE PRECISION,
    sma_200      DOUBLE PRECISION,
    ema_12       DOUBLE PRECISION,
    ema_26       DOUBLE PRECISION,
    macd         DOUBLE PRECISION,
    macd_signal  DOUBLE PRECISION,
    macd_hist    DOUBLE PRECISION,
    rsi_14       DOUBLE PRECISION,
    vol_sma_20   DOUBLE PRECISION,
    source       TEXT,
    PRIMARY KEY (symbol, timeframe, ts)
);
CREATE INDEX IF NOT EXISTS ohlcv_symbol_tf_idx
    ON ohlcv (symbol, timeframe);
"""


def _read_metrics(symbols: list[str] | None) -> pd.DataFrame:
    with _LOCK:
        con = connect()
        try:
            init_schema(con)
            df = con.execute(
                """
                SELECT symbol, as_of, section, metric, period, value_raw, value_num
                FROM fundamental_metrics
                """
            ).df()
        finally:
            con.close()
    if symbols:
        wanted = {s.strip().upper() for s in symbols if s.strip()}
        df = df[df["symbol"].isin(wanted)]
    return df


def _currency_by_symbol(df: pd.DataFrame) -> dict[str, str]:
    meta = df[
        (df["section"] == "financials meta")
        & (df["metric"].str.lower() == "unit")
    ]
    out: dict[str, str] = {}
    for row in meta.itertuples():
        out[row.symbol] = "USD" if "USD" in str(row.value_raw).upper() else "IDR"
    return out


def export_fundamentals(
    *,
    out_dir: str | Path | None = None,
    symbols: list[str] | None = None,
) -> str:
    """Write the three Postgres-ready Parquet files plus schema.sql."""
    out = Path(out_dir) if out_dir else DEFAULT_OUT
    out.mkdir(parents=True, exist_ok=True)

    df = _read_metrics(symbols)
    if df.empty:
        return (
            "export fundamentals: 0 rows in fundamental_metrics.\n"
            "Run farm_stockbit_fundamentals then "
            "run_data_transform(scope='fundamentals') first."
        )

    df["as_of"] = pd.to_datetime(df["as_of"], errors="coerce").dt.date
    df["period"] = df["period"].fillna("")
    dropped = df["metric"].str.match(_NOT_A_METRIC).fillna(False)
    df = df[~dropped]
    df["unit"] = [
        _unit_for(m, vr, vn)
        for m, vr, vn in zip(df["metric"], df["value_raw"], df["value_num"])
    ]
    currency = _currency_by_symbol(df)

    # Scalar rows picked up alongside a statement or series table have no
    # period, and a statement line without a period is not a statement line.
    is_fin = df["section"].str.startswith(_STATEMENT_PREFIXES) & df["period"].ne("")
    is_prof = df["section"].isin(PROFILE_SECTIONS) & ~is_fin

    fin_src = df[is_fin]
    split = [_split_section(s) for s in fin_src["section"]]
    fin = pd.DataFrame(
        {
            "symbol": fin_src["symbol"].values,
            "as_of": fin_src["as_of"].values,
            "statement": [s for s, _ in split],
            "period_type": [
                _normalise_period_type(pt) or _period_type_from(p)
                for (_, pt), p in zip(split, fin_src["period"])
            ],
            "period": fin_src["period"].values,
            "line_item": fin_src["metric"].values,
            "unit": fin_src["unit"].values,
            "currency": [currency.get(s, "IDR") for s in fin_src["symbol"]],
            "value": fin_src["value_num"].values,
            "value_raw": fin_src["value_raw"].values,
        }
    ).drop_duplicates(
        subset=["symbol", "statement", "period_type", "period", "line_item"]
    )

    prof_src = df[is_prof]
    prof = pd.DataFrame(
        {
            "symbol": prof_src["symbol"].values,
            "as_of": prof_src["as_of"].values,
            "category": prof_src["section"].values,
            "item": prof_src["metric"].values,
            "unit": prof_src["unit"].values,
            "value_raw": prof_src["value_raw"].values,
            "value_num": prof_src["value_num"].values,
        }
    ).drop_duplicates(subset=["symbol", "category", "item"])

    met = df[~is_fin & ~is_prof][
        ["symbol", "as_of", "section", "metric", "period", "unit", "value_raw", "value_num"]
    ].copy()
    met["_trust"] = [_section_trust(s) for s in met["section"]]
    met = (
        met.sort_values("_trust", kind="stable")
        .drop_duplicates(subset=["symbol", "metric", "period"])
        .drop(columns="_trust")
        .sort_values(["symbol", "section", "metric"])
    )

    written: list[tuple[str, int]] = []
    # DuckDB writes the parquet so the project keeps working without pyarrow.
    writer = duckdb.connect()
    try:
        for name, frame in (
            ("fundamental_metric", met),
            ("financial_statement_line", fin),
            ("company_profile", prof),
        ):
            path = out / f"{name}.parquet"
            writer.register("frame", frame)
            writer.execute(
                f"COPY (SELECT * FROM frame) TO '{path.as_posix()}' (FORMAT PARQUET)"
            )
            writer.unregister("frame")
            written.append((name, len(frame)))
    finally:
        writer.close()

    (out / "schema.sql").write_text(SCHEMA_SQL, encoding="utf-8")

    n_symbols = df["symbol"].nunique()
    lines = [
        f"export fundamentals -> {out}",
        f"symbols={n_symbols} source_rows={len(df)} "
        f"dropped_unnamed={int(dropped.sum())}",
        "",
    ]
    lines += [f"- {name}.parquet: {n} rows" for name, n in written]
    lines.append("- schema.sql: CREATE TABLE DDL for Postgres")
    lines.append("")
    lines.append(f"SAVED: {out / 'schema.sql'}")
    return "\n".join(lines)


CHARTS_DIR = Path("data") / "charts"


def export_ohlcv(
    *,
    out_dir: str | Path | None = None,
    timeframes: list[str] | None = None,
    charts_dir: str | Path | None = None,
) -> str:
    """Merge ``data/charts/{SYM}/{TF}.parquet`` into one Postgres-ready file.

    Default timeframes: ``5M``, ``30M``, ``1H``. Writes
    ``exports/postgres/ohlcv.parquet`` (+ refreshes ``schema.sql``).
    """
    out = Path(out_dir) if out_dir else DEFAULT_OUT
    out.mkdir(parents=True, exist_ok=True)
    root = Path(charts_dir) if charts_dir else CHARTS_DIR
    tfs = [
        t.strip().upper()
        for t in (timeframes or ["5M", "30M", "1H"])
        if str(t).strip()
    ]
    if not tfs:
        return "export ohlcv: no timeframes given"

    paths: list[Path] = []
    for tf in tfs:
        paths.extend(sorted(root.glob(f"*/{tf}.parquet")))
    # Skip _meta / non-symbol dirs already (glob is SYM/TF.parquet)
    paths = [p for p in paths if p.parent.name != "_meta" and p.is_file()]
    if not paths:
        return (
            f"export ohlcv: 0 parquet files under {root} for "
            f"timeframes={','.join(tfs)}"
        )

    dest = out / "ohlcv.parquet"
    con = duckdb.connect()
    try:
        con.execute("CREATE OR REPLACE TABLE ohlcv_export (symbol VARCHAR)")
        con.execute("DELETE FROM ohlcv_export")
        # Build empty typed table from first readable file.
        seed = paths[0]
        con.execute(
            f"""
            CREATE OR REPLACE TABLE ohlcv_export AS
            SELECT * FROM read_parquet('{seed.as_posix()}') WHERE 1=0
            """
        )
        # Drop extras we don't want in the Postgres handoff if present.
        have0 = {r[0].lower() for r in con.execute("DESCRIBE ohlcv_export").fetchall()}
        if "updated_at" in have0:
            con.execute("ALTER TABLE ohlcv_export DROP COLUMN updated_at")
        if "filename" in have0:
            con.execute("ALTER TABLE ohlcv_export DROP COLUMN filename")

        loaded = 0
        skipped: list[str] = []
        # Insert per file — avoids giant SQL lists and mid-farm race on one bad read.
        for p in paths:
            try:
                con.execute(
                    f"""
                    INSERT INTO ohlcv_export BY NAME
                    SELECT * FROM read_parquet('{p.as_posix()}')
                    WHERE symbol IS NOT NULL AND timeframe IS NOT NULL AND ts IS NOT NULL
                    """
                )
                loaded += 1
            except Exception as exc:  # noqa: BLE001
                skipped.append(f"{p.parent.name}/{p.name}: {type(exc).__name__}")
                logger.warning("skip %s: %s", p, exc)

        have = {r[0].lower() for r in con.execute("DESCRIBE ohlcv_export").fetchall()}

        def col_expr(name: str, cast: str) -> str:
            if name.lower() not in have:
                return f"CAST(NULL AS {cast}) AS {name}"
            return f"CAST({name} AS {cast}) AS {name}"

        select_parts = [
            "UPPER(CAST(symbol AS VARCHAR)) AS symbol",
            "UPPER(CAST(timeframe AS VARCHAR)) AS timeframe",
            "CAST(ts AS BIGINT) AS ts",
            col_expr("datetime", "VARCHAR"),
            col_expr("date", "INTEGER"),
            col_expr("open", "DOUBLE"),
            col_expr("high", "DOUBLE"),
            col_expr("low", "DOUBLE"),
            col_expr("close", "DOUBLE"),
            col_expr("volume", "DOUBLE"),
            col_expr("sma_5", "DOUBLE"),
            col_expr("sma_20", "DOUBLE"),
            col_expr("sma_50", "DOUBLE"),
            col_expr("sma_200", "DOUBLE"),
            col_expr("ema_12", "DOUBLE"),
            col_expr("ema_26", "DOUBLE"),
            col_expr("macd", "DOUBLE"),
            col_expr("macd_signal", "DOUBLE"),
            col_expr("macd_hist", "DOUBLE"),
            col_expr("rsi_14", "DOUBLE"),
            col_expr("vol_sma_20", "DOUBLE"),
            col_expr("source", "VARCHAR"),
        ]
        select_sql = ",\n                        ".join(select_parts)
        con.execute(
            f"""
            COPY (
                SELECT * EXCLUDE (rn) FROM (
                    SELECT
                        {select_sql},
                        ROW_NUMBER() OVER (
                            PARTITION BY
                                UPPER(CAST(symbol AS VARCHAR)),
                                UPPER(CAST(timeframe AS VARCHAR)),
                                CAST(ts AS BIGINT)
                            ORDER BY symbol
                        ) AS rn
                    FROM ohlcv_export
                ) WHERE rn = 1
                ORDER BY symbol, timeframe, ts
            ) TO '{dest.as_posix()}' (FORMAT PARQUET)
            """
        )
        stats = con.execute(
            f"""
            SELECT COUNT(*) AS n,
                   COUNT(DISTINCT symbol) AS syms,
                   COUNT(DISTINCT timeframe) AS tfs
            FROM read_parquet('{dest.as_posix()}')
            """
        ).fetchone()
        by_tf = con.execute(
            f"""
            SELECT timeframe, COUNT(*) AS n, COUNT(DISTINCT symbol) AS syms
            FROM read_parquet('{dest.as_posix()}')
            GROUP BY 1 ORDER BY 1
            """
        ).fetchall()
    finally:
        con.close()

    (out / "schema.sql").write_text(SCHEMA_SQL, encoding="utf-8")
    n, syms, n_tf = stats or (0, 0, 0)
    lines = [
        f"export ohlcv -> {out}",
        f"files_in={len(paths)} loaded={loaded} skipped={len(skipped)} "
        f"timeframes={','.join(tfs)}",
        f"- ohlcv.parquet: {n} rows symbols={syms} timeframes={n_tf}",
    ]
    for tf, n_rows, n_syms in by_tf:
        lines.append(f"  · {tf}: {n_rows} rows / {n_syms} symbols")
    if skipped:
        lines.append(f"- skipped sample: {'; '.join(skipped[:5])}")
    lines.append("- schema.sql: CREATE TABLE DDL for Postgres (incl. ohlcv)")
    lines.append(f"SAVED: {dest}")
    return "\n".join(lines)
